<?php
require_once 'config.php';

$password_to_set = 'admin123';
$new_hash = password_hash($password_to_set, PASSWORD_DEFAULT);

$stmt = $conn->prepare("UPDATE users SET password = ? WHERE username = 'super_admin'");
$stmt->bind_param("s", $new_hash);

if ($stmt->execute()) {
    echo "<h2>Success!</h2>";
    echo "<p>The password for 'super_admin' has been set to: <strong>$password_to_set</strong></p>";
    echo "<p>The hash generated by your server was: <code>$new_hash</code></p>";
    echo "<p><strong>Now, try logging in or refreshing test_db.php</strong></p>";
} else {
    echo "Error updating database: " . $conn->error;
}
?>
